require("config.lazy")
require("config.core")
require("config.oil")
require("config.transparent")
require("config.lualine")
require("config.treesitter")
require("config.mason")
require("config.autoclose")
